### ISSUE TITLE
add metric to expose key deletion status

### ISSUE THREAD

**Issue by rajatjindal** [kubernetes-sigs/aws-encryption-provider#25]
**What would you like to be added**:
metric to add key deletion status
**Why is this needed**:
if the key is marked to be deleted (accidentally or knowingly), i should be able to put an alert if i am still using it.

**Comment by rajatjindal** [comment]
Hi @micahhausler 

If this looks acceptable request, I am thinking that in plugin.New function, start a loop that runs every 1hr, and check for deletion status. Minimum schedule time for deletion in AWS is 7 days, so 1hr check should be sufficient. 

what do you think?

Thanks
Rajat Jindal

**Comment by micahhausler** [comment]
Marking a key for deletion renders it unavailable and all `kms:Encrypt` and `kms:Decrypt` operations will fail: https://docs.aws.amazon.com/kms/latest/developerguide/key-state.html

**Comment by rajatjindal** [comment]
ohk. and if i do not want the writes to happen unencrypted, can I just remove identity from there?

**Comment by micahhausler** [comment]
> ohk. and if i do not want the writes to happen unencrypted, can I just remove identity from there?

Correct, but if you don’t have any other providers, writes will fail.

**Comment by rajatjindal** [comment]
that makes sense. thank you.
