### ISSUE TITLE
cleaning up of socket file on restart of node

### ISSUE THREAD

**Issue by rajatjindal** [kubernetes-sigs/aws-encryption-provider#26]
**What happened**:

The master node was hard rebooted for some reason, it left the socket file hanging around. so the provider was not started as socket file already existed.

**What you expected to happen**:

The socket file should be cleaned up even if node is hard rebooted.

**How to reproduce it (as minimally and precisely as possible)**:

have aws-encryption-provider running, and restart the node from the cloud-provider console. (in this case it was AWS).

**Anything else we need to know?**:

**Environment**:

AWS cluster setup using kops
- Kubernetes version (use `kubectl version`):
- Encryption provider plugin version:
- Cloud provider configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jaredledvina** [comment]
We seem to be hitting a similar issue. In our cause the `aws-encryption-provider` fails to start up with:
```
INFO  [2019-07-31T02:19:08.281565298Z] k8s.io/kubernetes/aws-encryption-provider/main.go:89: Healthchecks listening on :8080 (pid: 15)
INFO  [2019-07-31T02:19:08.281637428Z] k8s.io/kubernetes/aws-encryption-provider/main.go:90: Server listening at /var/run/kmsplugin/socket.sock (pid: 15)
ERROR [2019-07-31T02:19:08.282051345Z] k8s.io/kubernetes/aws-encryption-provider/main.go:85: Failed to start server: failed to create listener: listen unix /var/run/kmsplugin/socket.sock: bind: address already in use (pid: 15)
```

In our setup, we have `aws-encryption-provider` configured as an initcontainer for our `/etc/kubelet.d/kube-apiserver.yml` static pod. It appears that kubelet was constantly trying to restart the pod but, this container continued to fail each restart. 

Even more oddly, I was able to resolve this by simply moving `/etc/kubelet.d/kube-apiserver.yml` out of that directory and then back in and the new pod started and the init containers kicked off without issue. 

Using `docker inspect` I see the bind mount we have configured for the socket:
```
      {
        "Type": "bind",
        "Source": "/etc/kubelet/pods/123456789/volumes/kubernetes.io~empty-dir/kms-provider-socket",
        "Destination": "/var/run/kmsplugin",
        "Mode": "",
        "RW": true,
        "Propagation": "rprivate"
      },
```
And I verified that locally the socket is left over in the mount:
```
$ ls -l /etc/kubelet/pods/123456789/volumes/kubernetes.io~empty-dir/kms-provider-socket
total 0
srwxr-xr-x 1 root root 0 Jul 31 02:03 socket.sock
```

Which in the static pod manifest is setup as:
```
    volumeMounts:
    - mountPath: /var/run/kmsplugin/
      name: kms-provider-socket
```
as an emptyDir:
```
  - downwardAPI:
  - emptyDir: {}
    name: kms-provider-socket
```

Not sure if the above issue helps here but, wanted to note that you're not the only one.

**Comment by micahhausler** [comment]
Closing. This should be done outside the process, as the provider can't reason about if an existing socket is in use or leftover

/close

**Comment by amitkatyal** [comment]
Hi, 
I am trying to configure aws-encryption-provider with K3s (single node cluster) on my ubuntu machine. I've provided the encryption configuration to kube-apiserver but k3s server itself is not starting and keep on complaining with below error.

"failed to create connection to unix socket: /var/run/kmsplugin/socket.sock, error: dial unix /var/run/kmsplugin/socket.sock: connect: connection refused"
  
I'm just trying to understand the sequence, 
1. Is Kube-ApiServer is expecting aws-encryption-provider (pod/service) to be up and running and listening on unix-domain socket ?. And it is not running than kube-apiserver will not start ?

**Comment by amitkatyal** [comment]
Above issue is fixed if I am running aws-encryption-provider separately before starting kube-apiserver.
However, k3s is still not  starting and stuck somewhere else.
