### ISSUE TITLE
Replace glog

### ISSUE THREAD

**Issue by micahhausler** [kubernetes-sigs/aws-encryption-provider#28]
**What would you like to be added**:

A different logging library

**Why is this needed**:

* glog is unmaintained 
* glog has known gotchas (see klog's [README](https://github.com/kubernetes/klog) for a full list)

**What are you proposing?**

Switch to either [klog](https://github.com/kubernetes/klog) or [zap](https://github.com/uber-go/zap).

klog would be an easy drop-in replacement, but doesn't provide structured logs for easy analysis.

Zap would be a little more work, but it is very fast, provides structured (JSON) logs

**Comment by Jukie** [comment]
I'd like to work on this, looks like all the changes will be in https://github.com/kubernetes-sigs/aws-encryption-provider/blob/master/cmd/server/main.go correct?

I plan on using zap, would (this pr)[https://github.com/cloudera/yunikorn-core/pull/3/files] be a good reference for implementing?

**Comment by micahhausler** [comment]
@Jukie I think that is where all the glog calls are today, but I think some additional debug log lines could be added to `pkg/plugin/plugin.go`

**Comment by micahhausler** [comment]
And yes,  yumikorn-core looks like a good reference. I'd also point you to `skuid/spec` ([`middlewares/middlewares.go`](https://github.com/skuid/spec/blob/master//middlewares/middlewares.go#L144-L167), [`spec.go`](https://github.com/skuid/spec/blob/master/spec.go) and  [`example/main.go`](https://github.com/skuid/spec/blob/master/example/main.go#L60-L64) ) for management of the zap config

**Comment by micahhausler** [comment]
/remove-lifecycle stale

@Jukie are you still interested in taking this on?

**Comment by micahhausler** [comment]
Fixed in #54 

/close
