### ISSUE TITLE
Improvement to documentation for configuring provider at cluster creation using kops

### ISSUE THREAD

**Issue by TajMahPaul** [kubernetes-sigs/aws-encryption-provider#29]
**What would you like to be added**:
Improvement in the Documentation for how to set-up this plugin using kops at cluster creation. I had a little bit of issues setting it up as a first-time user and would like to to contribute to the Docs to make it easier for others. 

**Why is this needed**:
Things that I found confusing as a first-time user:

1. How to set-up the `--encryption-provider` with kops and how to tell kops about the encryption configuration file.
- To set the flag you have to set the following flag in the kops cluster spec:
```
spec:
  encryptionConfig: true
```
- To let kops about the encryption configuration file you have to create a kops secret with a special `encryptionconfig` argument during cluster creation
```
kops create -f <-path_to_cluster_spec-> --state <-state_store->
kops create secret encryptionconfig -f <-path_to_encryption_config_file-> --state <-state_store-> --name <-cluster_name->
kops update cluster <-cluster_name-> --state <-state_store-> --yes
```

2. How to add `/var/run/kmsplugin` hostMount to api server spec using kops life cycle hooks

- I couldn't figure how to do this actually and referencing this [slack thread](https://kubernetes.slack.com/archives/C3QUFP0QM/p1522006624000051?thread_ts=1521946535.000039) from someone trying to do something similar in the kops-users channel, it doesn't seem trivial. What I ended up doing was mounting the unix socket in a host directory that was already mounted in the kube-apiserver ie. `/srv/kubernetes/socket.sock`. Not sure what your guys' opinion on this is.

3. Implementing kops `fileAssets` to run the static pod
- I had to add a label to the master instance groups in kops and then reference that label via `nodeSelector` and `tolerations` in the aws-provider pod spec to make sure the pod ran on the master node. So in the end my file asset looked something like this:
```
fileAssets:
- name: aws-encryption-provider.yaml
  ## Note if not path is specified the default path it /srv/kubernetes/assets/<name>
  path: /etc/kubernetes/manifests/aws-encryption-provider.yaml
  roles:
  - Master
  content: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: aws-encryption-provider
      namespace: kube-system
    spec:
      containers:
      - image: <image_of_aws_provider>
        name: aws-encryption-provider
        command:
        - /aws-encryption-provider
        - -key=<-arn_of_kms_key->
        - -region=<-region_of_kms_key->
        - -listen=/srv/kubernetes/socket.sock
        - -health-port=:8083
        ports:
        - containerPort: 8083
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8083
        volumeMounts:
        - mountPath: /srv/kubernetes
          name: kmsplugin
      hostNetwork: true
      volumes:
      - name: kmsplugin
        hostPath:
          path: /srv/kubernetes
          type: DirectoryOrCreate
      nodeSelector:
        dedicated: master
      tolerations:
      - key: dedicated
        operator: Equal
        value: master
        effect: NoSchedule
```
 
4. What the additional IAM policies look like. 
- Not too hard to find more like a nice to have. This is currently my spec. Again would love to hear your opinions on this as it would vary from user to user depending on their use case.
```
    node: |
      [  
        {
          "Effect": "Allow",
          "Action": [
            "kms:CreateGrant",
            "kms:Decrypt",
            "kms:DescribeKey",
            "kms:Encrypt",
            "kms:GenerateDataKey*",
            "kms:ReEncrypt*"
          ],
          "Resource": [
           <-arn_of_my_kms_key->
          ]
        }
      ]
    master: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "kms:CreateGrant",
            "kms:Decrypt",
            "kms:DescribeKey",
            "kms:Encrypt",
            "kms:GenerateDataKey*",
            "kms:ReEncrypt*"
          ],
          "Resource": [
            <-arn_of_my_kms_key->
          ]
        }
      ]
```
5. How to check that the provider is working
- First we create a secret: `kubectl create secret generic secret1 -n default --from-literal=mykey=mydata`
- Then we exec into the etcd-server: `kubectl exec -it -n kube-system $(kubectl get pods -n kube-system | grep etcd-manager-main | awk '{print $1}') bash`
- `cd /opt/etcd-v3.3.10-linux-amd64/`
- Then check the contents of our secret in etcd store:
```
ETCDCTL_API=3 ./etcdctl \
    --key /rootfs/etc/kubernetes/pki/kube-apiserver/etcd-client.key \
    --cert  /rootfs/etc/kubernetes/pki/kube-apiserver/etcd-client.crt \
    --cacert /rootfs/etc/kubernetes/pki/kube-apiserver/etcd-ca.crt  \
    --endpoints "https://etcd-a.internal.${CLUSTER}:4001" get /registry/secrets/default/secret1
```
&nbsp;&nbsp;&nbsp;-- output should be something like:
```
0m`�He.0�cryption-provider:�1x��%�B���#JP��J���*ȝ���΂@\n�96�^��ۦ�~0| *�H��
                    `q�*�J�.P��;&~��o#�O�8m��->8L��0�C3���A7�����~���f�V�ܬ���X��_��`�H#�D��z)+�81��qW��y��`�q��}1<LF, ��N��p����i*�aC#E�߸�s������s��l�?�a
�AźR������.��8H�4�O
```

**Comment by micahhausler** [comment]
Yea, this would be a great PR! There are a few changes to the above, but it'll be easier to discuss those on a PR diff.

**Comment by TajMahPaul** [comment]
Sounds good will get a PR up asap.

**Comment by vdoodala** [comment]
i am struggling to implement this using kops. Please let me know if i can help in any way.

**Comment by TajMahPaul** [comment]
> i am struggling to implement this using kops. Please let me know if i can help in any way.

What Part are you struggling with? I'm @pdhanda on the kubernetes slack channel if you want to msg me personally.
