### ISSUE TITLE
EKS Setup Guide

### ISSUE THREAD

**Issue by austince** [kubernetes-sigs/aws-encryption-provider#36]
**What would you like to be added**:

If it is possible to deploy this with EKS, it would be great to have a short guide like the one provided for Kops.

**Why is this needed**:

There seems to be a bit of confusion on whether or not this is possible:
- https://github.com/aws/containers-roadmap/issues/168
- https://github.com/aws/containers-roadmap/issues/168#issuecomment-502525125

Thank you!

**Comment by micahhausler** [comment]
EKS is a managed service, and doesn't provide configuration for the require control plane settings for customers to use this project with EKS.

You can follow support for this projected being used in EKS at aws/containers-roadmap#263

/close

**Comment by austince** [comment]
Thanks @micahhausler !
