### ISSUE TITLE
How to use the aws-encryption-provider with KMS endpoint

### ISSUE THREAD

**Issue by naqvisn** [kubernetes-sigs/aws-encryption-provider#47]
In my environment k8 can only access KMS service using KMS end point. is there any flag or setting to define KMS endpoint.
Can I define the env variable 
AWS_KMS_ENDPOINT:

**Comment by micahhausler** [comment]
There isn't a way to configure this today, but it would be a great first issue. You'd just need to add a new flag in [`/cmd/server/main.go`](https://github.com/kubernetes-sigs/aws-encryption-provider/blob/master/cmd/server/main.go#L33-L39), add a endpoint field to [`cloud.New()`](https://github.com/kubernetes-sigs/aws-encryption-provider/blob/master/pkg/cloud/cloud.go#L29) and set the [`aws.Config.Endpoint`](https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config) field

**Comment by micahhausler** [comment]
@naqvisn This has been fixed in $51. You can now set a `--kms-endpoint` flag on the encryption provider
