### ISSUE TITLE
How do you use this plugin?

### ISSUE THREAD

**Issue by masterdrdark** [kubernetes-sigs/aws-encryption-provider#9]
I am using Kubernetes 1.11.6 on AWS provisioned using KOPS

I'd like to enable KMS encryption provider for kubernetes secrets but I still need a KMS plugin. This is nice to know that a plugin for AWS KMS already exists but how do you install/use it?

**Comment by jcputney** [comment]
@sethpollack ? Anybody? I can't find any documentation on how to actually use this thing.

**Comment by micahhausler** [comment]
@masterdrdark @jcputney I've added a user guide in #17
